"""initial

Revision ID: f273b29c941a
Revises:
Create Date: 2026-04-18 18:26:32.089605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f273b29c941a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=True)
    op.create_index(op.f('ix_game_sort_order'), 'game', ['sort_order'], unique=False)
    op.bulk_insert(
        sa.table(
            'game',
            sa.column('name', sqlmodel.sql.sqltypes.AutoString()),
            sa.column('sort_order', sa.Integer()),
        ),
        [
            {'name': 'Quake III Arena', 'sort_order': 1},
            {'name': 'Diablo II', 'sort_order': 2},
            {'name': 'StarCraft', 'sort_order': 3},
            {'name': 'Half-Life', 'sort_order': 4},
            {'name': 'Unreal Tournament', 'sort_order': 5},
        ],
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),      
    sa.Column('game', sqlmodel.sql.sqltypes.AutoString(), nullable=False),      
    sa.Column('players_max', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_created_by'), 'room', ['created_by'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=True)        
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identity_address'), 'user', ['identity_address'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('nonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),     
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_nonce_identity_address'), 'nonce', ['identity_address'], unique=False)
    op.create_table('roommember',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_sort_order'), table_name='game')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_table('game')
    op.drop_table('roommember')
    op.drop_index(op.f('ix_nonce_identity_address'), table_name='nonce')        
    op.drop_table('nonce')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_identity_address'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_created_by'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###